// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegE2GK_RZ4Dqh3aVxX10B-xYwgfFTL-M',
    appId: '1:874148686673:web:7816117de24b14e3728170',
    messagingSenderId: '874148686673',
    projectId: 'make-my-day-now',
    authDomain: 'make-my-day-now.firebaseapp.com',
    storageBucket: 'make-my-day-now.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABELFcfUYDXpTYNIKt8mBsw2vzGQyhE-s',
    appId: '1:874148686673:android:b9cbbe378c6b132c728170',
    messagingSenderId: '874148686673',
    projectId: 'make-my-day-now',
    storageBucket: 'make-my-day-now.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAirSFrdX5RI3SEvUNvhygTxx5wk9G5nO4',
    appId: '1:874148686673:ios:0c5b3bd11b825dfe728170',
    messagingSenderId: '874148686673',
    projectId: 'make-my-day-now',
    storageBucket: 'make-my-day-now.firebasestorage.app',
    iosBundleId: 'com.example.makemyday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAirSFrdX5RI3SEvUNvhygTxx5wk9G5nO4',
    appId: '1:874148686673:ios:0c5b3bd11b825dfe728170',
    messagingSenderId: '874148686673',
    projectId: 'make-my-day-now',
    storageBucket: 'make-my-day-now.firebasestorage.app',
    iosBundleId: 'com.example.makemyday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDegE2GK_RZ4Dqh3aVxX10B-xYwgfFTL-M',
    appId: '1:874148686673:web:ffded5a20bb7b028728170',
    messagingSenderId: '874148686673',
    projectId: 'make-my-day-now',
    authDomain: 'make-my-day-now.firebaseapp.com',
    storageBucket: 'make-my-day-now.firebasestorage.app',
  );
}
